### ISSUE TITLE
filter 

### ISSUE THREAD

**Issue by shoyer** [kieferk/dfply#11]
This function is pretty essential for data analysis, and selecting by value is also one of the least ergonomic operations in pandas, so this would provide real value.

**Comment by shoyer** [comment]
Never mind, I see that `mask` does this.

**Comment by kieferk** [comment]
It's called `mask` in dfply since `filter` is reserved in python. It's in there in the `subset.py` file.

**Comment by shoyer** [comment]
Technically `filter` is just a builtin function -- you can certainly override it if desired (though that is often considered poor style).

**Comment by kieferk** [comment]
Yeah, "reserved" was not a correct choice of word. I am trying to avoid overriding python's built-in functions so that people can use `from dfply import *` without any rude surprises.
