### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by Make42** [kieferk/dfply#19]
In the readme is not instruction how to best install dfply. Could you add this, please? I especially would like to know how to install it into an Anaconda environment.

I checked out the requirements and, except for `pandas_ply`, I got them installed. However, I am not sure what `pandas_ply` is supposed to be. Do you mean https://github.com/coursera/pandas-ply? If so: From their github-page I understand that pandas-ply is not stable yet. So why would dfply be considered stable if it is build on pandas-ply?

**Comment by Make42** [comment]
Ok, I was able to simply install it with

     source activate myenv
     pip install dfply

Maybe this can be put into the README?

**Comment by complexgenome** [comment]
Go to

https://github.com/kieferk/dfply/issues/86
