### ISSUE TITLE
Mask with OR

### ISSUE THREAD

**Issue by Make42** [kieferk/dfply#28]
When using mask() it is possible to AND statements, but I don't see a  way of OR-ing statements. Could this please be added to the syntax somehow?

**Comment by bleearmstrong** [comment]
This already exists within mask. You just have to use parentheses with the or pipe.

```
df = pd.DataFrame({'x': [1, 2, 3], 'y': [4, 5, 6]})
df >> mask((X.x < 2) | (X.y > 5))
Out[24]: 
   x  y
0  1  4
2  3  6

```
