### ISSUE TITLE
Add `matches()` function?

### ISSUE THREAD

**Issue by crew102** [kieferk/dfply#57]
Greetings -

I noticed that dfply is missing the dplyr equivalent of `matches()`, which allows the user to pass in a regular expression when selecting columns (as opposed to a literal string - i.e., the `contains()` function). I've found `matches()` to be very useful in the past and would like to know if you're amenable to it being added to dfply? If so, I'd be happy to put together a PR.

Chris

**Comment by kieferk** [comment]
Always amenable to PRs! Sounds useful to me
