### ISSUE TITLE
Pandas throwing FutureWarnings on group_by

### ISSUE THREAD

**Issue by andrewkho** [kieferk/dfply#62]
Pandas is constantly throwing warnings like this and it makes the `group_by` unusable in my case, since it swamps all other console output.

```
.../python3.6/site-packages/dfply/base.py:307: FutureWarning: Interpreting tuple 'by' as a list of keys, rather than a single key. Use 'by=[...]' instead of 'by=(...)'. In the future, a tuple will always mean a single key.
```

When Pandas makes this change it will break the `group_by` so it's probably worth fixing now.

I think the way around this is to wrap the RHS with a `list(args)` [here](https://github.com/kieferk/dfply/blob/f80460eea4453bb484bc19cbea52dbef2af5f725/dfply/group.py#L7).

**Comment by andrewkho** [comment]
I have a working version on my fork, it passes all unittests (One of the tests needed to be fixed), I will submit a PR

**Comment by andrewkho** [comment]
PR #63

**Comment by kieferk** [comment]
Thank you - will merge this now.
