### ISSUE TITLE
DFPLY not working.....at all

### ISSUE THREAD

**Issue by jaybundy** [kieferk/dfply#64]
Sorry for being so new to this. But I can't get dfply to work....at all. It tells me select is not defined. I'm very frustrated. All I can find on the internet is praise for this package and not support for the fact that I can't get it to work. Below is some code.

from dfply import *
import pandas as pd

flight_data = pd.read_csv('nycflights13.csv')
flight_data.head()

AttributeError: module 'dfply' has no attribute 'select'

**Comment by sharpe5** [comment]
I don't see any code that uses dfply, only code that uses pandas.

Could you post some example code that uses dfply?

**Comment by sharpe5** [comment]
Try copying and pasting some of the example code that uses the built-in
diamonds dataframe.

**Comment by jaybundy** [comment]
Thanks for timely support.
It doesn't seem to matter. Running the above code snippet will produce the error I included, even if I don't actually call the select function.

The actual example code I'm trying to execute comes from:
https://towardsdatascience.com/dplyr-style-data-manipulation-with-pipes-in-python-380dcb137000 

from dfply import *
import pandas as pd

flight_data = pd.read_csv('nycflights13.csv')
flight_data.head()

(flight_data >>
 select(X.origin, X.dest, X.hour))

Here is the full error message:
  File "/Users/Jay/Programming/VSCode/Python/Google_python_class/Other_python_lessons/dfply1.py", line 3, in <module>
    from dfply import *
  File "/Users/Jay/Programming/VSCode/Python/Google_python_class/Other_python_lessons/dfply.py", line 11, in <module>
    dfply.select(X.origin, X.dest, X.hour))
AttributeError: module 'dfply' has no attribute 'select'

**Comment by jaybundy** [comment]
Interestingly,

If I just run this code:

import os
import pandas as pd
import dfply

print(dfply)

I still get:
AttributeError: module 'dfply' has no attribute 'select'

**Comment by kieferk** [comment]
Hello there. What version of python are you using? I don't think it would matter for this specifically, but dfply only works for python 3 now in case you're using python 2...

Can you open up a jupyter notebook or ipython console of and type:
```from dfply import *```

Then see if `select` is in the namespace?

**Comment by jaybundy** [comment]
Version 3.7.0. Interestingly, I seem to be able to get the code to work fine using the interpreter interactively. But when I try to use the package in a script (I write scripts in VS Code), even trying to run "import dfply" only with absolutely no other lines of code, I still get the message:

AttributeError: module 'dfply' has no attribute 'select'

That's weird, because at that point I haven't referenced select at all (as in the original post). But I have the same problem with dplython. Works fine interactively, can't use it in a script, claims it doesn't have select...but in both cases select shows up in help as well as dir and seems to work fine interactively.

**Comment by kieferk** [comment]
That is odd for sure. In the code above you posted:
```python
import os
import pandas as pd
import dfply

print(dfply)
```

Could you paste the exact error message you get here?

**Comment by jaybundy** [comment]
I believe I figured it out. I was naming the module I used to test the package dfply.py...which obviously broke the import. I'm so sorry to have troubled you guys over such a novice error. But I am very, very grateful for the persistent assistance. Happy Pythoning and Thanks!

**Comment by sharpe5** [comment]
Ah, that makes sense! I've done the same thing before but with a different package. Glad its sorted!
