### ISSUE TITLE
More general joining

### ISSUE THREAD

**Issue by jankislinger** [kieferk/dfply#68]
I have fixed a typo (`right_in` -> `right_on`) and reversed logic in one if statement in function that creates join parameters. See the changes here:
https://github.com/kieferk/dfply/compare/master...jankislinger:fix-join-multiple-by

Now it can be used to join tables on columns with different names:
```
import pandas as pd
from dfply import *

a = pd.DataFrame({
    'x1': ['A', 'B', 'C'],
    'x2': [1, 2, 3]
})
b = pd.DataFrame({
    'x4': ['A', 'B', 'D'],
    'x3': [True, False, True]
})

a >> inner_join(b, by=('x1', 'x4'))
```

It would be also convenient to be able to use multiple by statements. For example expression
```
a >> inner_join(b, by=['x1', ('x2', 'x3')])
```
could be used as
```
a.merge(b, left_on=['x1', 'x2'], right_on=['x1', 'x3'])
```
If you agree I would modify the code and create a PR.

**Comment by sharpe5** [comment]
Nice work! I remember I had trouble getting joins to work on multiple
columns. I ended up computing a "key" column which was a string
concatenation of three other columns, then joining on that. Perhaps this PR
will make this workaround unnecessary.

**Comment by sharpe5** [comment]
By convention, by=['x1', 'x2'] would use both columns from both tables.

If you want to use column x1 from table 1 and x2 from table 2, then create
a common column by setting x1 = x2 in table 2.

**Comment by jankislinger** [comment]
I agree that `by=['x1', 'x2']` should use both columns in both tables. But having to rename column before join is annoying. That's why I would use tuples for that case.

**Comment by kieferk** [comment]
Cool thank you. Will merge the PR now.
